name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ Compiler
      uses: actions/setup-cpp@v1
      with:
        compiler: gcc

    - name: Install dependencies
      run: sudo apt-get install -y cmake build-essential

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_CXX_STANDARD=20

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build
